// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.2
// source: accord.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StreamRequest_UserMsgType int32

const (
	StreamRequest_SEND_MSG   StreamRequest_UserMsgType = 0
	StreamRequest_EDIT_MSG   StreamRequest_UserMsgType = 1
	StreamRequest_DELETE_MSG StreamRequest_UserMsgType = 2
)

// Enum value maps for StreamRequest_UserMsgType.
var (
	StreamRequest_UserMsgType_name = map[int32]string{
		0: "SEND_MSG",
		1: "EDIT_MSG",
		2: "DELETE_MSG",
	}
	StreamRequest_UserMsgType_value = map[string]int32{
		"SEND_MSG":   0,
		"EDIT_MSG":   1,
		"DELETE_MSG": 2,
	}
)

func (x StreamRequest_UserMsgType) Enum() *StreamRequest_UserMsgType {
	p := new(StreamRequest_UserMsgType)
	*p = x
	return p
}

func (x StreamRequest_UserMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamRequest_UserMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_accord_proto_enumTypes[0].Descriptor()
}

func (StreamRequest_UserMsgType) Type() protoreflect.EnumType {
	return &file_accord_proto_enumTypes[0]
}

func (x StreamRequest_UserMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamRequest_UserMsgType.Descriptor instead.
func (StreamRequest_UserMsgType) EnumDescriptor() ([]byte, []int) {
	return file_accord_proto_rawDescGZIP(), []int{4, 0}
}

type StreamRequest_ConfMsgType int32

const (
	StreamRequest_EDIT_CHANNEL StreamRequest_ConfMsgType = 0
	StreamRequest_EDIT_SERVER  StreamRequest_ConfMsgType = 1
)

// Enum value maps for StreamRequest_ConfMsgType.
var (
	StreamRequest_ConfMsgType_name = map[int32]string{
		0: "EDIT_CHANNEL",
		1: "EDIT_SERVER",
	}
	StreamRequest_ConfMsgType_value = map[string]int32{
		"EDIT_CHANNEL": 0,
		"EDIT_SERVER":  1,
	}
)

func (x StreamRequest_ConfMsgType) Enum() *StreamRequest_ConfMsgType {
	p := new(StreamRequest_ConfMsgType)
	*p = x
	return p
}

func (x StreamRequest_ConfMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamRequest_ConfMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_accord_proto_enumTypes[1].Descriptor()
}

func (StreamRequest_ConfMsgType) Type() protoreflect.EnumType {
	return &file_accord_proto_enumTypes[1]
}

func (x StreamRequest_ConfMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamRequest_ConfMsgType.Descriptor instead.
func (StreamRequest_ConfMsgType) EnumDescriptor() ([]byte, []int) {
	return file_accord_proto_rawDescGZIP(), []int{4, 1}
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accord_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accord_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_accord_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accord_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accord_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_accord_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accord_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accord_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_accord_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accord_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accord_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_accord_proto_rawDescGZIP(), []int{3}
}

type StreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId uint64 `protobuf:"fixed64,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// Types that are assignable to Msg:
	//	*StreamRequest_UserMsg
	//	*StreamRequest_ConfMsg
	Msg isStreamRequest_Msg `protobuf_oneof:"msg"`
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accord_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accord_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_accord_proto_rawDescGZIP(), []int{4}
}

func (x *StreamRequest) GetChannelId() uint64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (m *StreamRequest) GetMsg() isStreamRequest_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *StreamRequest) GetUserMsg() *StreamRequest_UserMessage {
	if x, ok := x.GetMsg().(*StreamRequest_UserMsg); ok {
		return x.UserMsg
	}
	return nil
}

func (x *StreamRequest) GetConfMsg() *StreamRequest_ConfMessage {
	if x, ok := x.GetMsg().(*StreamRequest_ConfMsg); ok {
		return x.ConfMsg
	}
	return nil
}

type isStreamRequest_Msg interface {
	isStreamRequest_Msg()
}

type StreamRequest_UserMsg struct {
	UserMsg *StreamRequest_UserMessage `protobuf:"bytes,2,opt,name=user_msg,json=userMsg,proto3,oneof"`
}

type StreamRequest_ConfMsg struct {
	ConfMsg *StreamRequest_ConfMessage `protobuf:"bytes,3,opt,name=conf_msg,json=confMsg,proto3,oneof"`
}

func (*StreamRequest_UserMsg) isStreamRequest_Msg() {}

func (*StreamRequest_ConfMsg) isStreamRequest_Msg() {}

type StreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are assignable to Event:
	//	*StreamResponse_NewMsg
	//	*StreamResponse_UpdateMsg
	Event isStreamResponse_Event `protobuf_oneof:"event"`
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accord_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accord_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_accord_proto_rawDescGZIP(), []int{5}
}

func (x *StreamResponse) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (m *StreamResponse) GetEvent() isStreamResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *StreamResponse) GetNewMsg() *StreamResponse_NewMessage {
	if x, ok := x.GetEvent().(*StreamResponse_NewMsg); ok {
		return x.NewMsg
	}
	return nil
}

func (x *StreamResponse) GetUpdateMsg() *StreamResponse_UpdateMessage {
	if x, ok := x.GetEvent().(*StreamResponse_UpdateMsg); ok {
		return x.UpdateMsg
	}
	return nil
}

type isStreamResponse_Event interface {
	isStreamResponse_Event()
}

type StreamResponse_NewMsg struct {
	NewMsg *StreamResponse_NewMessage `protobuf:"bytes,2,opt,name=new_msg,json=newMsg,proto3,oneof"`
}

type StreamResponse_UpdateMsg struct {
	UpdateMsg *StreamResponse_UpdateMessage `protobuf:"bytes,3,opt,name=update_msg,json=updateMsg,proto3,oneof"`
}

func (*StreamResponse_NewMsg) isStreamResponse_Event() {}

func (*StreamResponse_UpdateMsg) isStreamResponse_Event() {}

type StreamRequest_UserMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    StreamRequest_UserMsgType `protobuf:"varint,1,opt,name=type,proto3,enum=Accord.StreamRequest_UserMsgType" json:"type,omitempty"`
	Content string                    `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *StreamRequest_UserMessage) Reset() {
	*x = StreamRequest_UserMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accord_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamRequest_UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest_UserMessage) ProtoMessage() {}

func (x *StreamRequest_UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_accord_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest_UserMessage.ProtoReflect.Descriptor instead.
func (*StreamRequest_UserMessage) Descriptor() ([]byte, []int) {
	return file_accord_proto_rawDescGZIP(), []int{4, 0}
}

func (x *StreamRequest_UserMessage) GetType() StreamRequest_UserMsgType {
	if x != nil {
		return x.Type
	}
	return StreamRequest_SEND_MSG
}

func (x *StreamRequest_UserMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type StreamRequest_ConfMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        StreamRequest_ConfMsgType `protobuf:"varint,1,opt,name=type,proto3,enum=Accord.StreamRequest_ConfMsgType" json:"type,omitempty"`
	Placeholder string                    `protobuf:"bytes,2,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
}

func (x *StreamRequest_ConfMessage) Reset() {
	*x = StreamRequest_ConfMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accord_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamRequest_ConfMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest_ConfMessage) ProtoMessage() {}

func (x *StreamRequest_ConfMessage) ProtoReflect() protoreflect.Message {
	mi := &file_accord_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest_ConfMessage.ProtoReflect.Descriptor instead.
func (*StreamRequest_ConfMessage) Descriptor() ([]byte, []int) {
	return file_accord_proto_rawDescGZIP(), []int{4, 1}
}

func (x *StreamRequest_ConfMessage) GetType() StreamRequest_ConfMsgType {
	if x != nil {
		return x.Type
	}
	return StreamRequest_EDIT_CHANNEL
}

func (x *StreamRequest_ConfMessage) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

type StreamResponse_NewMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderId uint64 `protobuf:"fixed64,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *StreamResponse_NewMessage) Reset() {
	*x = StreamResponse_NewMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accord_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamResponse_NewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse_NewMessage) ProtoMessage() {}

func (x *StreamResponse_NewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_accord_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse_NewMessage.ProtoReflect.Descriptor instead.
func (*StreamResponse_NewMessage) Descriptor() ([]byte, []int) {
	return file_accord_proto_rawDescGZIP(), []int{5, 0}
}

func (x *StreamResponse_NewMessage) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *StreamResponse_NewMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type StreamResponse_UpdateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Placeholder string `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
}

func (x *StreamResponse_UpdateMessage) Reset() {
	*x = StreamResponse_UpdateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accord_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamResponse_UpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse_UpdateMessage) ProtoMessage() {}

func (x *StreamResponse_UpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_accord_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse_UpdateMessage.ProtoReflect.Descriptor instead.
func (*StreamResponse_UpdateMessage) Descriptor() ([]byte, []int) {
	return file_accord_proto_rawDescGZIP(), []int{5, 1}
}

func (x *StreamResponse_UpdateMessage) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

var File_accord_proto protoreflect.FileDescriptor

var file_accord_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x41, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x25,
	0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xea, 0x03, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x09, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x41, 0x63, 0x63,
	0x6f, 0x72, 0x64, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x3e, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x66,
	0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x41, 0x63, 0x63,
	0x6f, 0x72, 0x64, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x66, 0x4d, 0x73, 0x67, 0x1a, 0x5e, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x66, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72,
	0x22, 0x39, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0c, 0x0a, 0x08, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x45, 0x44, 0x49, 0x54, 0x5f, 0x4d, 0x53, 0x47, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x44,
	0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x4d, 0x53, 0x47, 0x10, 0x02, 0x22, 0x30, 0x0a, 0x0b, 0x43,
	0x6f, 0x6e, 0x66, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x44,
	0x49, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x45, 0x44, 0x49, 0x54, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x01, 0x42, 0x05, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0xd0, 0x02, 0x0a, 0x0e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x3c, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4e, 0x65, 0x77, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x65, 0x77, 0x4d, 0x73, 0x67, 0x12,
	0x45, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x1a, 0x43, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x06, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x31, 0x0a, 0x0d, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x42, 0x07,
	0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x32, 0xb8, 0x01, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74,
	0x12, 0x36, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x2e, 0x41, 0x63, 0x63, 0x6f,
	0x72, 0x64, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x6f,
	0x75, 0x74, 0x12, 0x15, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x4c, 0x6f, 0x67, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x41, 0x63, 0x63, 0x6f,
	0x72, 0x64, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x15, 0x2e,
	0x41, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x71, 0x76, 0x6e, 0x74, 0x6d, 0x2f, 0x41, 0x63, 0x63, 0x6f, 0x72, 0x64, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_accord_proto_rawDescOnce sync.Once
	file_accord_proto_rawDescData = file_accord_proto_rawDesc
)

func file_accord_proto_rawDescGZIP() []byte {
	file_accord_proto_rawDescOnce.Do(func() {
		file_accord_proto_rawDescData = protoimpl.X.CompressGZIP(file_accord_proto_rawDescData)
	})
	return file_accord_proto_rawDescData
}

var file_accord_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_accord_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_accord_proto_goTypes = []interface{}{
	(StreamRequest_UserMsgType)(0),       // 0: Accord.StreamRequest.UserMsgType
	(StreamRequest_ConfMsgType)(0),       // 1: Accord.StreamRequest.ConfMsgType
	(*LoginRequest)(nil),                 // 2: Accord.LoginRequest
	(*LoginResponse)(nil),                // 3: Accord.LoginResponse
	(*LogoutRequest)(nil),                // 4: Accord.LogoutRequest
	(*LogoutResponse)(nil),               // 5: Accord.LogoutResponse
	(*StreamRequest)(nil),                // 6: Accord.StreamRequest
	(*StreamResponse)(nil),               // 7: Accord.StreamResponse
	(*StreamRequest_UserMessage)(nil),    // 8: Accord.StreamRequest.UserMessage
	(*StreamRequest_ConfMessage)(nil),    // 9: Accord.StreamRequest.ConfMessage
	(*StreamResponse_NewMessage)(nil),    // 10: Accord.StreamResponse.NewMessage
	(*StreamResponse_UpdateMessage)(nil), // 11: Accord.StreamResponse.UpdateMessage
	(*timestamp.Timestamp)(nil),          // 12: google.protobuf.Timestamp
}
var file_accord_proto_depIdxs = []int32{
	8,  // 0: Accord.StreamRequest.user_msg:type_name -> Accord.StreamRequest.UserMessage
	9,  // 1: Accord.StreamRequest.conf_msg:type_name -> Accord.StreamRequest.ConfMessage
	12, // 2: Accord.StreamResponse.timestamp:type_name -> google.protobuf.Timestamp
	10, // 3: Accord.StreamResponse.new_msg:type_name -> Accord.StreamResponse.NewMessage
	11, // 4: Accord.StreamResponse.update_msg:type_name -> Accord.StreamResponse.UpdateMessage
	0,  // 5: Accord.StreamRequest.UserMessage.type:type_name -> Accord.StreamRequest.UserMsgType
	1,  // 6: Accord.StreamRequest.ConfMessage.type:type_name -> Accord.StreamRequest.ConfMsgType
	2,  // 7: Accord.Chat.Login:input_type -> Accord.LoginRequest
	4,  // 8: Accord.Chat.Logout:input_type -> Accord.LogoutRequest
	6,  // 9: Accord.Chat.Stream:input_type -> Accord.StreamRequest
	3,  // 10: Accord.Chat.Login:output_type -> Accord.LoginResponse
	5,  // 11: Accord.Chat.Logout:output_type -> Accord.LogoutResponse
	7,  // 12: Accord.Chat.Stream:output_type -> Accord.StreamResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_accord_proto_init() }
func file_accord_proto_init() {
	if File_accord_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accord_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accord_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accord_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accord_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accord_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accord_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accord_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamRequest_UserMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accord_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamRequest_ConfMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accord_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamResponse_NewMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accord_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamResponse_UpdateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_accord_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*StreamRequest_UserMsg)(nil),
		(*StreamRequest_ConfMsg)(nil),
	}
	file_accord_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*StreamResponse_NewMsg)(nil),
		(*StreamResponse_UpdateMsg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accord_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accord_proto_goTypes,
		DependencyIndexes: file_accord_proto_depIdxs,
		EnumInfos:         file_accord_proto_enumTypes,
		MessageInfos:      file_accord_proto_msgTypes,
	}.Build()
	File_accord_proto = out.File
	file_accord_proto_rawDesc = nil
	file_accord_proto_goTypes = nil
	file_accord_proto_depIdxs = nil
}
